server:
  port: 10001

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true
        acks: all
        max.in.flight.requests.per.connection: 5
        compression.type: lz4
        linger.ms: 5
    admin:
      auto-create: true

platform:
  kafka:
    topics:
      raw-events: raw-events

logging:
  level:
    org.springframework.kafka: INFO
